commit_message: 'Crowdin: (%language%) Updated %original_file_name% translations'
append_commit_message: 
files:
  - source: /articles/*.Rmd.md
    ignore:
      - /articles/playstation-vita.Rmd.md
    translation: /articles/translations/%two_letters_code%/%file_name%.md
  - source: /resources/strings.toml
    translation: /resources/translations/%two_letters_code%.toml
  - source: /resources/generations.yaml
    translation: /resources/translations_generations/%two_letters_code%/generations.yaml
